"""
List of constant variables, to re-use and get a proper structure
"""

EXCHANGE_NSE = 'N'
EXCHANGE_BSE = 'B'
PRODUCT_TYPE_CASH = 'C'
PRODUCT_TYPE_DERIVATIVE = 'D'
SCRIPT_TYPE_EQUITY = 'EQ'
SCRIPT_TYPE_CALL = 'CE'
SCRIPT_TYPE_PUT = 'PE'
SCRIPT_TYPE_OTHERS = 'XX'
WS_MARKET_FEED = 'mf'
WS_MARKET_DEPTH = 'md'
WS_INDICES_SPOT_FEED = 'i'
WS_OPEN_INTEREST_FEED = 'oi'
WS_SUBSCRIBE = 's'
WS_UNSUBSCRIBE = 'u'
XTS_OPTION_CE = 3
XTS_OPTION_PE = 4
XTS_NSE_CASH = 1
XTS_NSE_DERIVATIVE = 2
CLIENT_ID = ''
NIFTY_INSTRUMENT_NAME = 'NIFTY'
NIFTY_SPOT_SCRIP_CODE = 999920000
CURR_W_EXPIRY_DATE = '2025-09-30'
CURR_M_EXPIRY_DATE = '2025-09-30'